add_newline = false

[character]
success_symbol = "[ ](bold green)"
error_symbol = "[ ](bold red)"

[line_break]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false
truncation_length = 3

[aws]
disabled = true
symbol = " "

[conda]
disabled = true
symbol = " "

[dart]
disabled = true
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[git_branch]
symbol = " "

[golang]
disabled = true
symbol = " "

[haskell]
disabled = true
symbol = " "

[hg_branch]
symbol = " "

[java]
disabled = true
symbol = " "

[julia]
disabled = true
symbol = " "

[memory_usage]
disabled = true
symbol = " "

[nim]
disabled = true
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
disabled = true
symbol = " "

[package]
disabled = true
symbol = " "

[perl]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[python]
disabled = true
symbol = " "

[ruby]
disabled = true
symbol = " "

[rust]
disabled = true
symbol = " "

[swift]
disabled = true
symbol = "ﯣ "

[terraform]
disabled = true

[lua]
disabled = true
